// Optimized icon loading - Metro-compatible approach
// Icons are grouped into core (always loaded) and secondary (loaded on first access)

// Core icons that are needed immediately (navigation, common UI)
const coreIcons = {
  // Navigation icons
  home: require("../assets/icons/home.png"),
  home2Outline: require("../assets/icons/home2-outline.png"),
  document2: require("../assets/icons/document2.png"),
  document2Outline: require("../assets/icons/document2-outline.png"),
  chat: require("../assets/icons/chat.png"),
  chatBubble2Outline: require("../assets/icons/chat-bubble2-outline.png"),
  user: require("../assets/icons/user.png"),
  userOutline: require("../assets/icons/user-outline.png"),
  
  // Essential UI icons
  back: require("../assets/icons/back.png"),
  search: require("../assets/icons/search.png"),
  plus: require("../assets/icons/plus.png"),
  more: require("../assets/icons/more.png"),
  moreCircle: require("../assets/icons/more-circle.png"),
  arrowBack: require("../assets/icons/arrow-back.png"),
  arrowDown: require("../assets/icons/arrow-down.png"),
  arrowUp: require("../assets/icons/arrow-up.png"),
  arrowRight: require("../assets/icons/arrow-right.png"),
  arrowLeft: require("../assets/icons/arrow-left.png"),
};

// Secondary icons - loaded lazily but with static requires
let secondaryIconsLoaded = false;
let secondaryIcons: { [key: string]: any } = {};

const loadSecondaryIcons = () => {
  if (secondaryIconsLoaded) return secondaryIcons;
  
  secondaryIcons = {
    addFileOutline: require("../assets/icons/add-file-outline.png"),
    addFile: require("../assets/icons/add-file.png"),
    bag: require("../assets/icons/bag.png"),
    bellOutline: require("../assets/icons/bell-outline.png"),
    bell: require("../assets/icons/bell.png"),
    bookmarkOutline: require("../assets/icons/bookmark-outline.png"),
    bookmark: require("../assets/icons/bookmark.png"),
    calendar: require("../assets/icons/calendar.png"),
    calendar2: require("../assets/icons/calendar2.png"),
    calendar3: require("../assets/icons/calendar3.png"),
    call: require("../assets/icons/call.png"),
    categoryOutline: require("../assets/icons/category-outline.png"),
    category: require("../assets/icons/category.png"),
    chatOutline: require("../assets/icons/chat-outline.png"),
    circleDown: require("../assets/icons/circle-down.png"),
    circleLeft: require("../assets/icons/circle-left.png"),
    circleRight: require("../assets/icons/circle-right.png"),
    circleUp: require("../assets/icons/circle-up.png"),
    discountOutline: require("../assets/icons/discount-outline.png"),
    discount: require("../assets/icons/discount.png"),
    document: require("../assets/icons/document.png"),
    documentOutline: require("../assets/icons/document-outline.png"),
    downloadFile: require("../assets/icons/download-file.png"),
    email: require("../assets/icons/email.png"),
    emailOutline: require("../assets/icons/email-outline.png"),
    exploreOutline: require("../assets/icons/explore-outline.png"),
    explore: require("../assets/icons/explore.png"),
    fileUploadOutline: require("../assets/icons/file-upload-outline.png"),
    fileUpload: require("../assets/icons/file-upload.png"),
    folderOutline: require("../assets/icons/folder-outline.png"),
    folder: require("../assets/icons/folder.png"),
    graph: require("../assets/icons/graph.png"),
    graphOutline: require("../assets/icons/graph-outline.png"),
    heartOutline: require("../assets/icons/heart-outline.png"),
    heart: require("../assets/icons/heart.png"),
    hide: require("../assets/icons/hide.png"),
    home2: require("../assets/icons/home2.png"),
    image: require("../assets/icons/image.png"),
    infoCircle: require("../assets/icons/info-circle.png"),
    locationOutline: require("../assets/icons/location-outline.png"),
    location: require("../assets/icons/location.png"),
    lock: require("../assets/icons/lock.png"),
    lockedComputerOutline: require("../assets/icons/locked-computer-outline.png"),
    logout: require("../assets/icons/logout.png"),
    loupe: require("../assets/icons/loupe.png"),
    microphone: require("../assets/icons/microphone.png"),
    moreHorizontal: require("../assets/icons/more-horizontal.png"),
    moreVertical: require("../assets/icons/more-vertical.png"),
    padlock: require("../assets/icons/padlock.png"),
    paperOutline: require("../assets/icons/paper-outline.png"),
    paper: require("../assets/icons/paper.png"),
    playOutline: require("../assets/icons/play-outline.png"),
    play: require("../assets/icons/play.png"),
    sendOutline: require("../assets/icons/send-outline.png"),
    send: require("../assets/icons/send.png"),
    settingOutline: require("../assets/icons/setting-outline.png"),
    setting2Outline: require("../assets/icons/setting2-outline.png"),
    settings: require("../assets/icons/settings.png"),
    shieldOutline: require("../assets/icons/shield-outline.png"),
    shield: require("../assets/icons/shield.png"),
    show: require("../assets/icons/show.png"),
    squareInfo: require("../assets/icons/square-info.png"),
    starOutline: require("../assets/icons/star-outline.png"),
    star: require("../assets/icons/star.png"),
    ticketOutline: require("../assets/icons/ticket-outline.png"),
    ticket: require("../assets/icons/ticket.png"),
    timeCircle: require("../assets/icons/time-circle.png"),
    trash: require("../assets/icons/trash.png"),
    unlock: require("../assets/icons/unlock.png"),
    upAndDownArrow: require("../assets/icons/up-and-down-arrow.png"),
    videoCameraOutline: require("../assets/icons/video-camera-outline.png"),
    videoCamera: require("../assets/icons/video-camera.png"),
    voiceCommandOutline: require("../assets/icons/voice-command-outline.png"),
    voiceOutline: require("../assets/icons/voice-outline.png"),
    voice: require("../assets/icons/voice.png"),
    volumeDown: require("../assets/icons/volume-down.png"),
    volumeUp: require("../assets/icons/volume-up.png"),
    wallet: require("../assets/icons/wallet.png"),
    walletOutline: require("../assets/icons/wallet-outline.png"),
    wallet2: require("../assets/icons/wallet2.png"),
    wallet2Outline: require("../assets/icons/wallet2-outline.png"),
    appleLogo: require("../assets/icons/apple-logo.png"),
    google: require("../assets/icons/google.png"),
    facebook: require("../assets/icons/facebook.png"),
    back2: require("../assets/icons/back2.png"),
    microphone2: require("../assets/icons/microphone2.png"),
    microphone3: require("../assets/icons/microphone3.png"),
    profile: require("../assets/icons/profile.png"),
    content: require("../assets/icons/content.png"),
    download: require("../assets/icons/download.png"),
    download2: require("../assets/icons/download2.png"),
    notification: require("../assets/icons/notification.png"),
    security: require("../assets/icons/security.png"),
    menu: require("../assets/icons/menu.png"),
    moreInformation: require("../assets/icons/more-information.png"),
    premium1: require("../assets/icons/premium1.png"),
    premium2: require("../assets/icons/premium2.png"),
    apple: require("../assets/icons/apple.png"),
    paypal: require("../assets/icons/paypal.png"),
    creditCard: require("../assets/icons/credit-card.png"),
    share: require("../assets/icons/share.png"),
    shareOutline: require("../assets/icons/share-outline.png"),
    internet: require("../assets/icons/internet.png"),
    internetOutline: require("../assets/icons/internet-outline.png"),
    downSquare: require("../assets/icons/down-square.png"),
    downSquare2: require("../assets/icons/down-square2.png"),
    rss: require("../assets/icons/rss.png"),
    playButton: require("../assets/icons/play-button.png"),
    pause: require("../assets/icons/pause.png"),
    backwardPlay: require("../assets/icons/backward-play.png"),
    forwardPlay: require("../assets/icons/forward-play.png"),
    forwardPlay2: require("../assets/icons/forward-play-2.png"),
    nextPlay: require("../assets/icons/next-play.png"),
    previousPlay: require("../assets/icons/previous-play.png"),
    speedometer: require("../assets/icons/speedometer.png"),
    speedometer2: require("../assets/icons/speedometer2.png"),
    stopwatch: require("../assets/icons/stopwatch.png"),
    cast: require("../assets/icons/cast.png"),
    history: require("../assets/icons/history.png"),
    userDefault: require("../assets/icons/user-default.png"),
    userDefault2: require("../assets/icons/user-default2.png"),
    userDefault3: require("../assets/icons/user-default3.png"),
    bell2: require("../assets/icons/bell2.png"),
    bell3: require("../assets/icons/bell3.png"),
    email2: require("../assets/icons/email2.png"),
    cartOutline: require("../assets/icons/cart-outline.png"),
    cart: require("../assets/icons/cart.png"),
    chatBubble: require("../assets/icons/chat-bubble.png"),
    chatBubble2: require("../assets/icons/chat-bubble2.png"),
    people: require("../assets/icons/people.png"),
    people2: require("../assets/icons/people2.png"),
    people3: require("../assets/icons/people3.png"),
    people4: require("../assets/icons/people4.png"),
    mastercard: require("../assets/icons/mastercard.png"),
    facebook2: require("../assets/icons/facebook2.png"),
    headset: require("../assets/icons/headset.png"),
    instagram: require("../assets/icons/instagram.png"),
    twitter: require("../assets/icons/twitter.png"),
    whatsapp: require("../assets/icons/whatsapp.png"),
    whatsapp2: require("../assets/icons/whatsapp2.png"),
    world: require("../assets/icons/world.png"),
    world2: require("../assets/icons/world2.png"),
    search2: require("../assets/icons/search2.png"),
    search3: require("../assets/icons/search3.png"),
    arrowDownSquare: require("../assets/icons/arrow-down-square.png"),
    arrowUpSquare: require("../assets/icons/arrow-up-square.png"),
    cancelSquare: require("../assets/icons/cancel-square.png"),
    cancelSquare2: require("../assets/icons/cancel-square-2.png"),
    telephone: require("../assets/icons/telephone.png"),
    telephoneOutline: require("../assets/icons/telephone-outline.png"),
    mediumVolume: require("../assets/icons/medium-volume.png"),
    noSound: require("../assets/icons/no-sound.png"),
    videoCamera2: require("../assets/icons/video-camera-2.png"),
    videoCamera2Off: require("../assets/icons/video-camera-2-off.png"),
    editPencil: require("../assets/icons/edit_pencil.png"),
    editText: require("../assets/icons/edit-text.png"),
    edit: require("../assets/icons/edit_pencil.png"),
    signature: require("../assets/icons/signature.png"),
    bookmark2: require("../assets/icons/bookmark2.png"),
    bookmark2Outline: require("../assets/icons/bookmark2-outline.png"),
    notificationBell: require("../assets/icons/notification-bell.png"),
    notificationBell2: require("../assets/icons/notification-bell2.png"),
    filter: require("../assets/icons/filter.png"),
    filter2: require("../assets/icons/filter2.png"),
    filter3: require("../assets/icons/filter3.png"),
    filter4: require("../assets/icons/filter4.png"),
    box: require("../assets/icons/box.png"),
    rating: require("../assets/icons/rating.png"),
    star2: require("../assets/icons/star2.png"),
    star3: require("../assets/icons/star3.png"),
    star4: require("../assets/icons/star4.png"),
    users: require("../assets/icons/users.png"),
    users2: require("../assets/icons/users2.png"),
    time: require("../assets/icons/time.png"),
    clockTime: require("../assets/icons/clock-time.png"),
    figma: require("../assets/icons/figma.png"),
    heart2: require("../assets/icons/heart2.png"),
    heart2Outline: require("../assets/icons/heart2_outline.png"),
    heart3: require("../assets/icons/heart3.png"),
    heart4: require("../assets/icons/heart4.png"),
    check: require("../assets/icons/check.png"),
    dashboardOutline: require("../assets/icons/dashboard-outline.png"),
    dashboard: require("../assets/icons/dashboard.png"),
    dashboard2: require("../assets/icons/dashboard2.png"),
    user2: require("../assets/icons/user2.png"),
    user3: require("../assets/icons/user3.png"),
    user4: require("../assets/icons/user4.png"),
    status: require("../assets/icons/status.png"),
  };
  
  secondaryIconsLoaded = true;
  return secondaryIcons;
};

// Create the icons object with lazy loading for secondary icons
const icons = new Proxy(coreIcons, {
  get(target: any, prop: string) {
    // Return core icons immediately
    if (prop in target) {
      return target[prop];
    }
    
    // Load secondary icons on first access
    const secondary = loadSecondaryIcons();
    if (prop in secondary) {
      return secondary[prop];
    }
    
    // Fallback for unknown icons
    console.warn(`Icon "${prop}" not found`);
    return undefined;
  }
});

export default icons;